services:
  app:
    container_name: bank_app_auth_server
    restart: always
    build:
      context: .
      dockerfile: authserver/Dockerfile
      args:
        NODE_ENV: ${NODE_ENV}
        AUTH_PORT: ${AUTH_PORT}
    ports:
      - "${AUTH_PORT}:${AUTH_PORT}"
    environment:
      NODE_ENV: ${NODE_ENV}
      AUTH_PORT: ${AUTH_PORT}
      DB_URI: ${DB_URI}
    depends_on:
      - mongo

  server:
    container_name: bank_app_server
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      NODE_ENV: ${NODE_ENV}
      SERVER_PORT: ${SERVER_PORT}
      DB_URI: ${DB_URI}
    depends_on:
      - mongo

  mongo:
    container_name: mongodb_bank_app
    image: mongo
    volumes:
      - mongodb:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodb:
