name: Docker Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t dudge1/bank_app_express_server:latest -f server/Dockerfile .
          docker push dudge1/bank_app_express_server:latest
          docker build -t dudge1/bank_app_auth_server:latest -f authserver/Dockerfile .
          docker push dudge1/bank_app_auth_server:latest
          